//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string UniqueInstanceID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string TransactionCode { get; set; }
        public decimal TransactionAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.TimeSpan TransactionTime { get; set; }
        public string ChequeNumber { get; set; }
        public string DrCrIndicator { get; set; }
        public string BankName { get; set; }
        public string BranchCode { get; set; }
        public string ReferenceNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Identifier { get; set; }
    }
}
